import { Roboto } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from '@/components/ThemeProvider';


const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "CSEC Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="min-h-screen bg-gray-50">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}