import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/toaster';
import '@/styles/globals.css';
import { Roboto } from "next/font/google";

const roboto = Roboto({ 
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata = {
  title: "CSEC Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable}`} suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased">
        <ThemeProvider>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}